services:
  db:
    image: mariadb
    restart: always
    env_file:
      - ../packages/backend/.env.development
    volumes:
      - ./volumes/mariadb_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: 
      context: ../packages/backend
    stdin_open: true
    tty: true
    env_file:
      - ../packages/backend/.env.development
    volumes:
      - ../packages/backend/src:/app/src
      - ../packages/backend/logs:/app/logs
      - ../packages/backend/tsconfig.json:/app/tsconfig.json
    expose:
      - "3000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    expose:
      - "80"
    volumes:
      - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  mariadb_data: 