services:
  frontend:
    build: 
      context: ../packages/frontend
    stdin_open: true
    tty: true
    env_file:
      - ../packages/frontend/.env.development
    command: npm start
    expose:
      - "3000"
    volumes:
      - ../packages/frontend:/app
      # - ../packages/frontend/node_modules:/app/node_modules

  nginx:
    build: 
      context: ./nginx
    container_name: gestion-esports-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
      - phpmyadmin 