services:
  db:
    image: mariadb
    restart: always
    env_file:
      - ../packages/backend/.env.production
    volumes:
      - ./volumes/mariadb_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  frontend:
    build: 
      context: ../packages/frontend
    env_file:
      - ../packages/frontend/.env.production
    command: npm run build
    volumes:
      - ../packages/frontend/dist:/usr/share/nginx/html:ro

  backend:
    build: 
      context: ../packages/backend
    env_file:
      - ../packages/backend/.env.production
    ports:
      - "3000:3000"


  nginx:
    build: 
      context: ./nginx
    container_name: gestion-esports-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ../packages/frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - phpmyadmin 